version: '3'

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: padminisys/wpk8s-ui
    ports:
      - '3001:3000'
